### ISSUE TITLE
base home directory error

### ISSUE THREAD

**Issue by BKhalili** [BergmannLab/metabomodules-docker#10]
Running the docker using: metabomodules --input=./input.csv --container=singularity
I get the following error on the terminal:
--------------------------------------------------------------------------------
METABOMODULES
Preparing container, please wait...
Running container, please wait...

Exectution took 1 seconds
mv: cannot stat `/h-sara0/bita/.metabomodules/code/output/2*': No such file or directory

and in the log file I get:
[91mERROR  : Base home directory does not exist within the container: /h-sara0
[0m[31mABORT  : Retval = 255

**Comment by mattiat** [comment]
This is not an issue related to the software in itself. Singularity cannot be properly run on our server with CentOS 6.
