### ISSUE TITLE
allow to run methods selectively

### ISSUE THREAD

**Issue by mattiat** [BergmannLab/metabomodules-docker#5]
Add option for running ISA, ACP, PCA individually if a user wants to only try one of the methods. The default should be false so that if the user doesn’t specify all the methods are ran.

**Comment by mattiat** [comment]
can now do, e.g.: metabomodules [...] --method=acp

**Comment by BKhalili** [comment]
in line 242 when defining parser argument user_method you need to add "default=not_set", right now it doesn't run any of the methods if one doesn't specify.

**Comment by mattiat** [comment]
Works for me, I can't reproduce.
Could you send me your full output?



I RUN THE FOLLOWING
$ metabomodules --input=../_test.csv --container=docker --output=../output 

------------------STARTING METABOMODULES PIPELINE--------------------
WARNING: the number of permutations has been set to 99
         For the filtering work reliably, we recommend values > 9999.

------RUNNING MODULARIZATION METHODS: GENERATING PSEUDOSPACTRA-------

---------------------------RUNNING ACP-------------------------------

Flag for removing feature-feature pairs in a same neighboring distance= True 
[...]

---------------------------RUNNING PCA-------------------------------


---------------------------RUNNING ISA-------------------------------

/ --- ISA wrapper 2018-06-25/18:00
[...]

**Comment by BKhalili** [comment]
Right, it works now!
